name: update-themes
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - uses: actions/checkout@v3
        with:
          ref: fix-ci
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.5"
      - name: Update submodules
        shell: bash
        working-directory: ./cmd/hugothemesitebuilder/build
        run: |
          git config --global user.email "bep@users.noreply.github.com"
          git config --global user.name "bep"
          go install github.com/gohugoio/hugo@v0.110.0
          hugo mod get -u
          git add .
          git commit -am "[Bot] Update themes"
          git log -p -3

